title: ArrrrCamp 2014 - October 2nd & 3rd, 2014
author: ArrrrCamp
subtitle: "A conference for the modern developer"
description: "A conference for the modern developer"

source: ./_source
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:date/:title
markdown: rdiscount
pygments: true
