title: ArrrrCamp
author: ArrrrCamp
subtitle: "A conference for the modern developer"
description: "A conference for the modern developer"
tagline: October 2nd & 3rd, 2014

source: ./_source
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:year/:month/:day/:title
markdown: kramdown
pygments: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
