title: ArrrrCamp
author: ArrrrCamp
subtitle: "A conference for the modern Rubyist"
description: "A conference for the modern Rubyist"
tagline: October 1st & 2nd, 2015

source: ./_source
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
